"""empty message

Revision ID: 1527181386a5
Revises: 4315b9c34b81
Create Date: 2025-08-22 09:06:30.441055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1527181386a5'
down_revision = '4315b9c34b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehiculo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=False))
        batch_op.drop_column('genero')
        batch_op.drop_column('altura')
        batch_op.drop_column('color_piel')
        batch_op.drop_column('nombre')
        batch_op.drop_column('color_pelo')

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=50), nullable=False))
        batch_op.drop_column('nombre')
        batch_op.drop_column('clima')
        batch_op.drop_column('terreno')
        batch_op.drop_column('poblacion')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('consumables', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('length', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('crew', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('passengers', sa.String(length=50), nullable=False))
        batch_op.drop_column('pasajeros')
        batch_op.drop_column('tripulacion')
        batch_op.drop_column('nombre')
        batch_op.drop_column('longitud')
        batch_op.drop_column('fabricante')
        batch_op.drop_column('modelo')
        batch_op.drop_column('costo_creditos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costo_creditos', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fabricante', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tripulacion', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pasajeros', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('length')
        batch_op.drop_column('consumables')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('model')
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('username')

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terreno', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clima', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('name')

    with op.batch_alter_table('personaje', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_pelo', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('color_piel', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('altura', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('genero', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')
        batch_op.drop_column('name')

    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('vehiculo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
