"""empty message

Revision ID: 35c811ba2ee2
Revises: 1527181386a5
Create Date: 2025-08-22 09:08:39.956966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c811ba2ee2'
down_revision = '1527181386a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('fecha_subscripcion', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fecha_subscripcion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
